Update aks-setup-and-deploy.yml

diff --git a/.github/workflows/aks-setup-and-deploy.yml b/.github/workflows/aks-setup-and-deploy.yml
--- a/.github/workflows/aks-setup-and-deploy.yml
+++ b/.github/workflows/aks-setup-and-deploy.yml
@@ -117,6 +117,31 @@ jobs:
           kubectl delete secret ingest-api-secret --ignore-not-found
           kubectl create secret generic ingest-api-secret --from-literal=API_KEY="${{ secrets.API_KEY }}"
 
+  create_db_k8s_secret:
+    name: Create or Update AKS Secret for ingest-db
+    runs-on: ubuntu-latest
+    needs: aggregate_validation_results
+    if: ${{ contains(needs.aggregate_validation_results.outputs.aggregated_matrix, '"service_name":"ingest-db"') }}
+    steps:
+      - uses: actions/checkout@v4
+  
+      - uses: azure/login@v1
+        with:
+          creds: ${{ github.event.inputs.azure_credentials || secrets.AZURE_CREDENTIALS }}
+  
+      - run: |
+          az aks get-credentials \
+          --resource-group ${{ github.event.inputs.resource_group || secrets.RESOURCE_GROUP }} \
+          --name ${{ github.event.inputs.aks_name || secrets.AKS_NAME }} --admin
+  
+      - run: |
+          if [[ -z "${{ secrets.DB_KEY }}" ]]; then
+            echo "DB_KEY secret is missing!"
+            exit 1
+          fi
+          kubectl delete secret ingest-db-secret --ignore-not-found
+          kubectl create secret generic ingest-db-secret --from-literal=DB_KEY="${{ secrets.DB_KEY }}"
+
   setup_cluster:
     name: Setup AKS Cluster Without Running Jobs
     runs-on: ubuntu-latest
